version: '3'

services:
  api:
    build: .
    ports:
      - '3000:3000'
    environment:
      - MONGODB_URI=mongodb://mongo:27017/auth-profile
    depends_on: mongo

  mongo:
    image: mongo:7
    restart: always
    ports:
      - '27017:27017'
