services:
  api:
    build: .
    ports:
      - '4000:3000'
    env_file:
      - .env.example
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    restart: always
    ports:
      - '27017:27017'
